# @package _group_

_target_: pytorch_lightning.Trainer
deterministic: True
precision: 16
accelerator: auto
devices: 1
max_epochs: 2
logger: 
  - _target_: pytorch_lightning.loggers.WandbLogger
    project: lightning_MNIST_test
    tags: ["hydra"]
callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_acc_epoch
    mode: max
    patience: 3
    verbose: True
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_acc_epoch
    mode: max
    save_top_k: 1
    verbose: True


